import io
import os
import glob
import shutil
from typing import Any, Dict, List, Optional, Union

import ase.io
import numpy as np
from ase import Atoms
from pymatgen.io.vasp import Incar

from .params import potcar_default


# ===========================================================================
# VASP specific functions
# ===========================================================================


def prepare_vasp_inputs(
    structure: Atoms,
    pp_path: str,
    kspacing: float,
    incar_dict: dict,
    incar_params: str = '',
):
    """Prepare VASP input files (POSCAR, KPOINTS, POTCAR, INCAR) in current directory.

    Parameters
    ----------
    structure : Atoms
        Atomic structure.
    pp_path : str
        Path to VASP pseudopotential directory.
    kspacing : float
        K-point spacing in 1/Å. Used to generate KPOINTS.
    incar_dict : dict
        Base INCAR parameters dictionary.
    incar_params : str, optional
        Additional INCAR parameters in KEY=VALUE format string (will override defaults).
    """
    # Write POSCAR
    ase.io.write('POSCAR', structure, format='vasp')

    # Write KPOINTS
    if kspacing is not None:
        prepare_kpoints(structure, kspacing)

    # Write POTCAR
    if pp_path:
        prepare_potcar(structure, pp_path)

    # Write INCAR
    prepare_incar(incar_dict=incar_dict, incar_params=incar_params)


def prepare_kpoints(structure: Atoms, kspacing: float):
    """Generate KPOINTS file based on k-point spacing.

    Parameters
    ----------
    structure : Atoms
        Atomic structure (used to get cell parameters).
    kspacing : float
        K-point spacing in 1/Å.
    """
    rec_cell = structure.cell.reciprocal().array

    kpoints = []
    for i in range(3):
        length = np.linalg.norm(rec_cell[i])
        nk = max(1, length / kspacing)
        kpoints.append(nk)
    kpoints = symmetric_kpoints(structure, kpoints)

    with open('KPOINTS', 'w') as f:
        f.write("KPOINTS generated by QDYN\n")
        f.write("0\n")
        f.write("Gamma\n")
        f.write(f"{kpoints[0]} {kpoints[1]} {kpoints[2]}\n")
        f.write("0.0 0.0 0.0\n")


def symmetric_kpoints(structure: Atoms, kpoints: list[float]) -> list[int]:
    return [int(k) + 1 for k in kpoints]


def prepare_potcar(structure: Atoms, pp_path: str):
    """Generate POTCAR file by concatenating pseudopotentials.

    Parameters
    ----------
    structure : Atoms
        Atomic structure (used to get element types).
    pp_path : str
        Path to VASP pseudopotential directory.
    """
    # Get unique elements in order of appearance
    symbols = structure.get_chemical_symbols()
    unique_symbols = []
    for s in symbols:
        if s not in unique_symbols:
            unique_symbols.append(s)

    if os.path.isdir(pp_path):
        with open('POTCAR', 'w') as outf:
            for symbol in unique_symbols:
                # Try common POTCAR naming conventions
                try:
                    potcars = glob.glob(os.path.join(pp_path, "*POTCAR*"))

                    potcar_file = None
                    for candidate in potcars:
                        if symbol in candidate:
                            potcar_file = candidate
                            break
                    if potcar_file is None:
                        raise FileNotFoundError
                except:
                    potcar_file = os.path.join(
                        pp_path, potcar_default[symbol], 'POTCAR'
                    )

                if not os.path.isfile(potcar_file):
                    raise FileNotFoundError(
                        f"POTCAR for element {symbol} not found in {pp_path}. "
                    )

                with open(potcar_file, 'r') as inf:
                    shutil.copyfileobj(inf, outf)


def prepare_incar(
    incar_dict: dict,
    incar_params: str = '',
):
    """Generate INCAR file for VASP calculation.

    Parameters are applied in the following order (later overrides earlier):
    1. incar_dict (base parameters)
    2. incar_params (additional parameters in KEY=VALUE format string)

    Parameters
    ----------
    incar_dict : dict
        Base INCAR parameters dictionary.
    incar_params : str, optional
        Additional INCAR parameters in KEY=VALUE format string.
    """
    incar = Incar.from_dict(incar_dict)
    if incar_params:
        incar_append = Incar.from_str(incar_params)
        incar.update(incar_append)

    incar.write_file('INCAR')
