import re
from typing import Any, Literal

_INCAR = {
    'ISTART': 0,
    'ISPIN': 1,
    'LREAL': 'Auto',
    'PREC': 'Normal',
    'LWAVE': False,
    'LCHARG': False,
    'NWRITE': 1,
    'KPAR': 2,
    'NCORE': 8,
    'ISMEAR': 0,
    'SIGMA': 0.1,
    'ENCUT': 500,
}
_OPENMX = {
    "system.currentdirectory":   "./",
    "system.name":               "qdyn",
    "data.path":                 "../../DFT_DATA19",
    "scf.xctype":                "GGA-PBE",
    "scf.spinpolarization":      "off",
    "scf.electronictemperature":  300.0,
    "scf.energycutoff":           150.0,
    "scf.maxiter":                90,
    "scf.eigenvaluesolver":      "band",
    "scf.proexpn.vna":           "on",
    "md.type":                   "nomd",
    "md.maxiter":                 1,
}

PARAMS_DEFAULT = {
    'sr': {
        'vasp': {
            **_INCAR,
            'NELM': 90,
            'NELMIN': 6,
            'EDIFF': 1e-8,
            'NSW': 100,
            'IBRION': 2,
            'ISIF': 2,
            'EDIFFG': -0.01,
        }
    },
    'nvt': {
        'vasp': {
            **_INCAR,
            'ALGO': 'Normal',
            'NELMIN': 4,
            'NELM': 120,
            'EDIFF': 1e-6,
            'ISYM': 0,
            'IBRION': 0,
            'NSW': 1000,
            'POTIM': 1,
            'SMASS': 0,
            'NBLOCK': 4,
            'TEBEG': 300,
            'TEEND': 300,
        },
        'openmx': {
            **_OPENMX,
            'scf.maxiter': 120,
            'scf.criterion': 1e-6,
            'md.timestep': 1.0,
            'md.maxiter': 1000,
            'md.type': 'NVT_VS',
            'md.tempcontrol': ['2', '1    4 300 0.0', '1000 4 300 0.0']
        } #TODO: add other parameters for MD
    },
    'nve': {
        'vasp': {
            **_INCAR,
            'ALGO': 'Normal',
            'NELMIN': 4,
            'NELM': 120,
            'EDIFF': 1e-6,
            'ISYM': 0,
            'IBRION': 0,
            'NSW': 5000,
            'POTIM': 1,
            'SMASS': -3,
            'NBLOCK': 1,
        },
        'openmx': {
            **_OPENMX,
            'scf.maxiter': 120,
            'scf.criterion': 1e-6,
            'md.type': 'NVE',
            'md.timestep': 1.0,
            'md.maxiter': 5000
        }
    },
    'scf': {
        'vasp': {
            **_INCAR,
            'LORBIT': 11,
            # 'NEDOS': 2001,
            'NELM': 120,
            'EDIFF': 1e-6,
            'LWAVE': True,
            'LCHARG': True,
            'ICHARG': 1,
        },
        'openmx': {
            **_OPENMX,
            'scf.maxiter': 120,
            'scf.criterion': 1e-6,
            'md.type': 'Nomd',
            'md.maxiter': 1
        } # TODO: add charge density and wavefunction output parameters for openmx
    },
}

# MD5 hash pattern for uploaded file validation (32-char lowercase hex).
# Used by InputT validator and /upload/hash endpoint.
HASH_PATTERN = re.compile(r'^[0-9a-f]{32}$')


XC_MAPPING = {
    'vasp':{
        'PBE': '',
        'PBEsol': 'PS',
        'PW91': '91',
    },
    'openmx': {
        'PBE': 'GGA-PBE',
    }
}

BAK_FNAMES = {
    'vasp': [
        'POSCAR', 'CONTCAR', 'XDATCAR', 
        'OSZICAR', 'OUTCAR', 'INCAR', 'KPOINTS', 'POTCAR',
    ],
    'openmx': ['qdyn.dat', 'qdyn.extxyz'],
    'nequip': ['nequip_in.vasp', 'nequip_out.vasp'],
    'mace': ['mace_in.vasp', 'mace_out.vasp'],
}
CHG_FNAME = {
    'vasp': 'CHGCAR',
    'openmx': 'stub',
}
INPUT_FNAMES = {
    'vasp': {'INCAR', 'KPOINTS', 'POSCAR', 'POTCAR'},
    'openmx': {'qdyn.dat'}
}

STRU_FNAME_MAPPING = {
    'vasp': 'POSCAR',
    'nequip': 'nequip_in.vasp',
    'mace': 'mace_in.vasp',
    'openmx': 'qdyn.dat',
}
STRU2_FNAME_MAPPING = {
    'vasp': 'CONTCAR',
    'nequip': 'nequip_out.vasp',
    'mace': 'mace_out.vasp',
    'openmx': 'qdyn.extxyz',
}
TRAJ_FNAME_MAPPING = {
    'vasp': 'XDATCAR',
    'nequip': 'qdyn.extxyz',
    'mace': 'qdyn.extxyz',
    'openmx': 'qdyn.md',
}

STRU_FORMAT_MAPPING = {
    'vasp': 'vasp',
    'nequip': 'vasp',
    'mace': 'vasp',
    'openmx': 'openmx-dat',
}
STRU2_FORMAT_MAPPING = {
    'vasp': 'vasp',
    'nequip': 'vasp',
    'mace': 'vasp',
    'openmx': 'extxyz',
}
# ASE format strings for reading/writing trajectory files per software.
# Used by read_strus(), write_strus(), and upload validation.
TRAJ_FORMAT_MAPPING = {
    'vasp': 'vasp-xdatcar',
    # COMPATIBLE USES BELOW
    'extxyz': 'extxyz',
    'nequip': 'extxyz',
    'mace': 'extxyz',
    'openmx': 'openmx-md',
}

SUPPORTED_STRUCTURE_FORMATS = {
    'vasp',
    'cif',
    'extxyz',
    'openmx-dat',
}
SUPPORTED_TRAJECTORY_FORMATS = {
    'vasp-xdatcar',
    'extxyz',
    'openmx-md',
}

# MLFFs
NEQUIP_PRETRAINED_MODELS = (
    'mir-group/NequIP-OAM-L',
    'mir-group/NequIP-OAM-M',
    'mir-group/NequIP-OAM-S',
    'mir-group/NequIP-OAM-XL',
    'mir-group/Allegro-OAM-L',
)

type NEQUIP_PRETRAINED_MODELS_TYPE = Literal[
    'mir-group/NequIP-OAM-L',
    'mir-group/NequIP-OAM-M',
    'mir-group/NequIP-OAM-S',
    'mir-group/NequIP-OAM-XL',
    'mir-group/Allegro-OAM-L',
]

MACE_PRETRAINED_MODELS = (
    'small',
    'medium',
    'large',
    'small-0b',
    'medium-0b',
    'small-0b2',
    'medium-0b2',
    'large-0b2',
    'medium-0b3',
)

type MACE_PRETRAINED_MODELS_TYPE = Literal[
    'small',
    'medium',
    'large',
    'small-0b',
    'medium-0b',
    'small-0b2',
    'medium-0b2',
    'large-0b2',
    'medium-0b3',
]

MACE_PRETRAINED_MODEL_URLS = {
    'small': 'https://github.com/ACEsuit/mace-mp/releases/download/mace_mp_0/2023-12-10-mace-128-L0_energy_epoch-249.model',
    'medium': 'https://github.com/ACEsuit/mace-mp/releases/download/mace_mp_0/2023-12-03-mace-128-L1_epoch-199.model',
    'large': 'https://github.com/ACEsuit/mace-mp/releases/download/mace_mp_0/MACE_MPtrj_2022.9.model',
    'small-0b': 'https://github.com/ACEsuit/mace-mp/releases/download/mace_mp_0b/mace_agnesi_small.model',
    'medium-0b': 'https://github.com/ACEsuit/mace-mp/releases/download/mace_mp_0b/mace_agnesi_medium.model',
    'small-0b2': 'https://github.com/ACEsuit/mace-mp/releases/download/mace_mp_0b2/mace-small-density-agnesi-stress.model',
    'medium-0b2': 'https://github.com/ACEsuit/mace-mp/releases/download/mace_mp_0b2/mace-medium-density-agnesi-stress.model',
    'large-0b2': 'https://github.com/ACEsuit/mace-mp/releases/download/mace_mp_0b2/mace-large-density-agnesi-stress.model',
    'medium-0b3': 'https://github.com/ACEsuit/mace-mp/releases/download/mace_mp_0b3/mace-mp-0b3-medium.model',
}

HAMGNN_PRETRAINED_MODELS = (
    'universal2.0',
)

type HAMGNN_PRETRAINED_MODELS_TYPE = Literal[
    'universal2.0',
]

HAMGNN_PRETRAINED_CONFIGS: dict[str, Any] = {
    'universal2.0': {
        'ham_type': 'openmx',
        'nao_max': 26,
        'add_H0': True,
        'cutoff': 26.0,
        'irreps_edge_sh': '0e + 1o + 2e + 3o + 4e + 5o + 6e',
        'irreps_node_features': '128x0e+32x1o+32x1e+32x2o+32x2e+32x3o+32x3e+16x4o+16x4e+16x5o+8x5e+8x6e',
        'num_layers': 3,
        'adv': {
            'legacy_edge_update': True,
            'cutoff_func': 'cos',
            'num_radial': 128,
            'num_types': 128,
            'rbf_func': 'bessel',
            'set_features': True,
            'radial_MLP': [128, 128],
            'use_corr_prod': True,
            'num_hidden_features': 32,
            'use_kan': False,
            'radius_scale': 1.01,
            'build_internal_graph': False,
        },
    },
}


# PBE
PSEUDO_POTENTIAL = {
    'vasp': {
        'H': 'H',
        'He': 'He',
        'Li': 'Li_sv',
        'Be': 'Be',
        'B': 'B',
        'C': 'C',
        'N': 'N',
        'O': 'O',
        'F': 'F',
        'Ne': 'Ne',
        'Na': 'Na_pv',
        'Mg': 'Mg',
        'Al': 'Al',
        'Si': 'Si',
        'P': 'P',
        'S': 'S',
        'Cl': 'Cl',
        'Ar': 'Ar',
        'K': 'K_sv',
        'Ca': 'Ca_sv',
        'Sc': 'Sc_sv',
        'Ti': 'Ti_sv',
        'V': 'V_sv',
        'Cr': 'Cr_pv',
        'Mn': 'Mn_pv',
        'Fe': 'Fe',
        'Co': 'Co',
        'Ni': 'Ni',
        'Cu': 'Cu',
        'Zn': 'Zn',
        'Ga': 'Ga_d',
        'Ge': 'Ge_d',
        'As': 'As',
        'Se': 'Se',
        'Br': 'Br',
        'Kr': 'Kr',
        'Rb': 'Rb_sv',
        'Sr': 'Sr_sv',
        'Y': 'Y_sv',
        'Zr': 'Zr_sv',
        'Nb': 'Nb_sv',
        'Mo': 'Mo_sv',
        'Tc': 'Tc_pv',
        'Ru': 'Ru_pv',
        'Rh': 'Rh_pv',
        'Pd': 'Pd',
        'Ag': 'Ag',
        'Cd': 'Cd',
        'In': 'In_d',
        'Sn': 'Sn_d',
        'Sb': 'Sb',
        'Te': 'Te',
        'I': 'I',
        'Xe': 'Xe',
        'Cs': 'Cs_sv',
        'Ba': 'Ba_sv',
        'La': 'La',
        'Ce': 'Ce',
        'Pr': 'Pr_3',
        'Nd': 'Nd_3',
        'Pm': 'Pm_3',
        'Sm': 'Sm_3',
        'Eu': 'Eu_2',
        'Gd': 'Gd_3',
        'Tb': 'Tb_3',
        'Dy': 'Dy_3',
        'Ho': 'Ho_3',
        'Er': 'Er_3',
        'Tm': 'Tm_3',
        'Yb': 'Yb_2',
        'Lu': 'Lu_3',
        'Hf': 'Hf_pv',
        'Ta': 'Ta_pv',
        'W': 'W_sv',
        'Re': 'Re',
        'Os': 'Os',
        'Ir': 'Ir',
        'Pt': 'Pt',
        'Au': 'Au',
        'Hg': 'Hg',
        'Tl': 'Tl_d',
        'Pb': 'Pb_d',
        'Bi': 'Bi_d',
        'Po': 'Po_d',
        'At': 'At',
        'Rn': 'Rn',
        'Fr': 'Fr_sv',
        'Ra': 'Ra_sv',
        'Ac': 'Ac',
        'Th': 'Th',
        'Pa': 'Pa',
        'U': 'U',
        'Np': 'Np',
        'Pu': 'Pu',
        'Am': 'Am',
        'Cm': 'Cm',
    },
    'openmx': {
        "H": "H_PBE19",
        "He": "He_PBE19",
        "Li": "Li_PBE19",
        "Be": "Be_PBE19",
        "B": "B_PBE19",
        "C": "C_PBE19",
        "N": "N_PBE19",
        "O": "O_PBE19",
        "F": "F_PBE19",
        "Ne": "Ne_PBE19",
        "Na": "Na_PBE19",
        "Mg": "Mg_PBE19",
        "Al": "Al_PBE19",
        "Si": "Si_PBE19",
        "P": "P_PBE19",
        "S": "S_PBE19",
        "Cl": "Cl_PBE19",
        "Ar": "Ar_PBE19",
        "K": "K_PBE19",
        "Ca": "Ca_PBE19",
        "Sc": "Sc_PBE19",
        "Ti": "Ti_PBE19",
        "V": "V_PBE19",
        "Cr": "Cr_PBE19",
        "Mn": "Mn_PBE19",
        "Fe": "Fe_PBE19H",
        "Co": "Co_PBE19H",
        "Ni": "Ni_PBE19H",
        "Cu": "Cu_PBE19H",
        "Zn": "Zn_PBE19H",
        "Ga": "Ga_PBE19",
        "Ge": "Ge_PBE19",
        "As": "As_PBE19",
        "Se": "Se_PBE19",
        "Br": "Br_PBE19",
        "Kr": "Kr_PBE19",
        "Rb": "Rb_PBE19",
        "Sr": "Sr_PBE19",
        "Y": "Y_PBE19",
        "Zr": "Zr_PBE19",
        "Nb": "Nb_PBE19",
        "Mo": "Mo_PBE19",
        "Tc": "Tc_PBE19",
        "Ru": "Ru_PBE19",
        "Rh": "Rh_PBE19",
        "Pd": "Pd_PBE19",
        "Ag": "Ag_PBE19",
        "Cd": "Cd_PBE19",
        "In": "In_PBE19",
        "Sn": "Sn_PBE19",
        "Sb": "Sb_PBE19",
        "Te": "Te_PBE19",
        "I": "I_PBE19",
        "Xe": "Xe_PBE19",
        "Cs": "Cs_PBE19",
        "Ba": "Ba_PBE19",
        "La": "La_PBE19",
        "Ce": "Ce_PBE19",
        "Pr": "Pr_PBE19",
        "Nd": "Nd_PBE19",
        "Pm": "Pm_PBE19",
        "Sm": "Sm_PBE19",
        "Dy": "Dy_PBE19",
        "Ho": "Ho_PBE19",
        "Lu": "Lu_PBE19",
        "Hf": "Hf_PBE19",
        "Ta": "Ta_PBE19",
        "W": "W_PBE19",
        "Re": "Re_PBE19",
        "Os": "Os_PBE19",
        "Ir": "Ir_PBE19",
        "Pt": "Pt_PBE19",
        "Au": "Au_PBE19",
        "Hg": "Hg_PBE19",
        "Tl": "Tl_PBE19",
        "Pb": "Pb_PBE19",
        "Bi": "Bi_PBE19",
    }
}

ALL_ORBITALS = {
    'openmx': {
        # openmx 4.0 recommendations
        'X': {'Kr10.0-s1p1': ('Quick',), 'Kr10.0-s2p1d1': ('Standard',)},
        'H': {'H5.0-s2': ('Quick',), 'H6.0-s2p1': ('Standard', 13, 14, 19, 26)},
        'He': {'He8.0-s1p1': ('Quick',), 'He8.0-s2p1': ('Standard', 13, 14, 19, 26)},
        'Li': {'Li8.0-s3p1': ('Quick',), 'Li8.0-s3p2': ('Standard', 14, 19, 26)},
        'Be': {'Be7.0-s2p1': ('Quick',), 'Be7.0-s2p2': ('Standard', 13, 14, 19, 26)},
        'B': {'B7.0-s2p2': ('Quick',), 'B7.0-s2p2d1': ('Standard', 13, 14, 19, 26)},
        'C': {'C6.0-s2p2': ('Quick',), 'C6.0-s2p2d1': ('Standard', 13, 14, 19, 26)},
        'N': {'N6.0-s2p2': ('Quick',), 'N6.0-s2p2d1': ('Standard', 13, 14, 19, 26)},
        'O': {'O6.0-s2p2': ('Quick',), 'O6.0-s2p2d1': ('Standard', 13, 14, 19, 26)},
        'F': {'F6.0-s2p2': ('Quick',), 'F6.0-s2p2d1': ('Standard', 13, 14, 19, 26)},
        'Ne': {'Ne9.0-s2p2': ('Quick',), 'Ne9.0-s2p2d1': ('Standard', 13, 14, 19, 26)},
        'Na': {'Na9.0-s3p2': ('Quick',), 'Na9.0-s3p2d1': ('Standard', 14, 19, 26)},
        'Mg': {'Mg9.0-s2p2': ('Quick', 13), 'Mg9.0-s3p2d1': ('Standard', 14, 19, 26)},
        'Al': {'Al7.0-s2p1d1': ('Quick',), 'Al7.0-s2p2d1': ('Standard', 13, 14, 19, 26)},
        'Si': {'Si7.0-s2p1d1': ('Quick',), 'Si7.0-s2p2d1': ('Standard', 13, 14, 19, 26)},
        'P': {'P7.0-s2p2d1': ('Quick', 13, 14, 19, 26), 'P7.0-s2p2d1f1': ('Standard',)},
        'S': {'S7.0-s2p2d1': ('Quick', 13, 14, 19, 26), 'S7.0-s2p2d1f1': ('Standard',)},
        'Cl': {'Cl7.0-s2p2d1': ('Quick', 13, 14, 19, 26), 'Cl7.0-s2p2d1f1': ('Standard',)},
        'Ar': {'Ar9.0-s2p2d1': ('Quick', 13, 14, 19, 26), 'Ar9.0-s2p2d1f1': ('Standard',)},
        'K': {'K10.0-s3p2': ('Quick',), 'K10.0-s3p2d1': ('Standard', 14, 19, 26)},
        'Ca': {'Ca9.0-s3p2': ('Quick',), 'Ca9.0-s3p2d1': ('Standard', 14, 19, 26)},
        'Sc': {'Sc9.0-s2p2d1': ('Quick', 13), 'Sc9.0-s3p2d1': ('Standard', 14, 19, 26)},
        'Ti': {'Ti7.0-s2p2d1': ('Quick', 13), 'Ti7.0-s3p2d1': ('Standard', 14, 19, 26)},
        'V': {'V6.0-s2p2d1': ('Quick', 13), 'V6.0-s3p2d1': ('Standard', 14, 19, 26)},
        'Cr': {'Cr6.0-s2p2d1': ('Quick', 13), 'Cr6.0-s3p2d1': ('Standard', 14, 19, 26)},
        'Mn': {'Mn6.0-s2p2d1': ('Quick', 13), 'Mn6.0-s3p2d1': ('Standard', 14, 19, 26)},
        'Fe': {'Fe5.5H-s2p2d1': ('Quick', 13), 'Fe5.5H-s3p2d1': ('Standard', 14, 19, 26)},
        'Co': {'Co6.0H-s2p2d1': ('Quick', 13), 'Co6.0H-s3p2d1': ('Standard', 14, 19, 26)},
        'Ni': {'Ni6.0H-s2p2d1': ('Quick', 13), 'Ni6.0H-s3p2d1': ('Standard', 14, 19, 26)},
        'Cu': {'Cu6.0H-s2p2d1': ('Quick', 13), 'Cu6.0H-s3p2d1': ('Standard', 14, 19, 26)},
        'Zn': {'Zn6.0H-s2p2d1': ('Quick', 13), 'Zn6.0H-s3p2d1': ('Standard', 14, 19, 26)},
        'Ga': {'Ga7.0-s2p2d1': ('Quick', 13, 14), 'Ga7.0-s3p2d2': ('Standard', 19, 26)},
        'Ge': {'Ge7.0-s2p1d1': ('Quick', 13, 14), 'Ge7.0-s3p2d2': ('Standard', 19, 26)},
        'As': {'As7.0-s3p2d1': ('Quick', 14), 'As7.0-s3p2d2': ('Standard', 19, 26)},
        'Se': {'Se7.0-s3p2d1': ('Quick', 14), 'Se7.0-s3p2d2': ('Standard', 19, 26)},
        'Br': {'Br7.0-s3p2d1': ('Quick', 14), 'Br7.0-s3p2d2': ('Standard', 19, 26)},
        'Kr': {'Kr10.0-s2p2d1': ('Quick', 13, 14), 'Kr10.0-s3p2d2': ('Standard', 19, 26)},
        'Rb': {'Rb11.0-s2p2d1': ('Quick', 13, 14), 'Rb11.0-s3p2d2': ('Standard', 19, 26)},
        'Sr': {'Sr10.0-s2p2d1': ('Quick', 13, 14), 'Sr10.0-s3p2d2': ('Standard', 19, 26)},
        'Y': {'Y10.0-s3p2d1': ('Quick', 14), 'Y10.0-s3p2d2': ('Standard', 19, 26)},
        'Zr': {'Zr7.0-s3p2d1': ('Quick', 14), 'Zr7.0-s3p2d2': ('Standard', 19, 26)},
        'Nb': {'Nb7.0-s3p2d1': ('Quick', 14), 'Nb7.0-s3p2d2': ('Standard', 19, 26)},
        'Mo': {'Mo7.0-s3p2d1': ('Quick', 14), 'Mo7.0-s3p2d2': ('Standard', 19, 26)},
        'Tc': {'Tc7.0-s3p2d1': ('Quick', 14), 'Tc7.0-s3p2d2': ('Standard', 19, 26)},
        'Ru': {'Ru7.0-s3p2d1': ('Quick', 14), 'Ru7.0-s3p2d2': ('Standard', 19, 26)},
        'Rh': {'Rh7.0-s3p2d1': ('Quick', 14), 'Rh7.0-s3p2d2': ('Standard', 19, 26)},
        'Pd': {'Pd7.0-s3p2d1': ('Quick', 14), 'Pd7.0-s3p2d2': ('Standard', 19, 26)},
        'Ag': {'Ag7.0-s3p2d1': ('Quick', 14), 'Ag7.0-s3p2d2': ('Standard', 19, 26)},
        'Cd': {'Cd7.0-s3p2d1': ('Quick', 14), 'Cd7.0-s3p2d2': ('Standard', 19, 26)},
        'In': {'In7.0-s3p2d1': ('Quick', 14), 'In7.0-s3p2d2': ('Standard', 19, 26)},
        'Sn': {'Sn7.0-s3p2d1': (14,), 'Sn7.0-s3p2d2': (19, 26), 'Sn7.0-s2p2d2': ('Quick',), 'Sn7.0-s3p2d3': ('Standard',)}, # v4.0 recommend s2p2d2, s3p2d3
        'Sb': {'Sb7.0-s3p2d1': ('Quick', 14), 'Sb7.0-s3p2d2': ('Standard', 19, 26)},
        'Te': {'Te7.0-s3p2d2': ('Quick', 19), 'Te7.0-s3p2d2f1': ('Standard', 26)},
        'I': {'I7.0-s3p2d2': ('Quick', 19), 'I7.0-s3p2d2f1': ('Standard', 26)},
        'Xe': {'Xe11.0-s3p2d1': ('Quick', 14), 'Xe11.0-s3p2d2': ('Standard', 19, 26)},
        'Cs': {'Cs12.0-s3p2d1': ('Quick', 14), 'Cs12.0-s3p2d2': ('Standard', 19, 26)},
        'Ba': {'Ba10.0-s3p2d1': ('Quick', 14), 'Ba10.0-s3p2d2': ('Standard', 19, 26)},
        'La': {'La8.0-s3p2d1f1': ('Quick',), 'La8.0-s3p2d2f1': ('Standard', 26)},
        'Ce': {'Ce8.0-s3p2d1f1': ('Quick',), 'Ce8.0-s3p2d2f1': ('Standard', 26)},
        'Pr': {'Pr8.0-s3p2d1f1': ('Quick',), 'Pr8.0-s3p2d2f1': ('Standard', 26)},
        'Nd': {'Nd8.0-s3p2d1f1': ('Quick',), 'Nd8.0-s3p2d2f1': ('Standard', 26)},
        'Pm': {'Pm8.0-s3p2d1f1': ('Quick',), 'Pm8.0-s3p2d2f1': ('Standard', 26)},
        'Sm': {'Sm8.0-s3p2d1f1': ('Quick',), 'Sm8.0-s3p2d2f1': ('Standard', 26)},
        'Dy': {'Dy8.0-s3p2d1f1': ('Quick',), 'Dy8.0-s3p2d2f1': ('Standard', 26)},
        'Ho': {'Ho8.0-s3p2d1f1': ('Quick',), 'Ho8.0-s3p2d2f1': ('Standard', 26)},
        'Lu': {'Lu8.0-s3p2d2': ('Quick', 19), 'Lu8.0-s3p2d2f1': ('Standard', 26)},
        'Hf': {'Hf9.0-s3p2d2': ('Quick', 19), 'Hf9.0-s3p2d2f1': ('Standard', 26)},
        'Ta': {'Ta7.0-s3p2d2': ('Quick', 19), 'Ta7.0-s3p2d2f1': ('Standard', 26)},
        'W': {'W7.0-s3p2d2': ('Quick', 19), 'W7.0-s3p2d2f1': ('Standard', 26)},
        'Re': {'Re7.0-s3p2d2': ('Quick', 19), 'Re7.0-s3p2d2f1': ('Standard', 26)},
        'Os': {'Os7.0-s3p2d2': ('Quick', 19), 'Os7.0-s3p2d2f1': ('Standard', 26)},
        'Ir': {'Ir7.0-s3p2d2': ('Quick', 19), 'Ir7.0-s3p2d2f1': ('Standard', 26)},
        'Pt': {'Pt7.0-s3p2d2': ('Quick', 19), 'Pt7.0-s3p2d2f1': ('Standard', 26)},
        'Au': {'Au7.0-s3p2d2': ('Quick', 19), 'Au7.0-s3p2d2f1': ('Standard', 26)},
        'Hg': {'Hg8.0-s3p2d2': ('Quick', 19), 'Hg8.0-s3p2d2f1': ('Standard', 26)},
        'Tl': {'Tl8.0-s3p2d2': ('Quick', 19), 'Tl8.0-s3p2d2f1': ('Standard', 26)},
        'Pb': {'Pb8.0-s3p2d2': ('Quick', 19), 'Pb8.0-s3p2d2f1': ('Standard', 26)},
        'Bi': {'Bi8.0-s3p2d2': ('Quick', 19), 'Bi8.0-s3p2d2f1': ('Standard', 26)},
    }
}

ORBITAL_BASIS = {}

VALENCE_ELECTRONS = {
    'openmx': {
        "H": 1,
        "He": 2,
        "Li": 3,
        "Be": 2,
        "B": 3,
        "C": 4,
        "N": 5,
        "O": 6,
        "F": 7,
        "Ne": 8,
        "Na": 9,
        "Mg": 8,
        "Al": 3,
        "Si": 4,
        "P": 5,
        "S": 6,
        "Cl": 7,
        "Ar": 8,
        "K": 9,
        "Ca": 10,
        "Sc": 11,
        "Ti": 12,
        "V": 13,
        "Cr": 14,
        "Mn": 15,
        "Fe": 16,
        "Co": 17,
        "Ni": 18,
        "Cu": 19,
        "Zn": 20,
        "Ga": 13,
        "Ge": 4,
        "As": 15,
        "Se": 6,
        "Br": 7,
        "Kr": 8,
        "Rb": 9,
        "Sr": 10,
        "Y": 11,
        "Zr": 12,
        "Nb": 13,
        "Mo": 14,
        "Tc": 15,
        "Ru": 14,
        "Rh": 15,
        "Pd": 16,
        "Ag": 17,
        "Cd": 12,
        "In": 13,
        "Sn": 14,
        "Sb": 15,
        "Te": 16,
        "I": 7,
        "Xe": 8,
        "Cs": 9,
        "Ba": 10,
        "La": 11,
        "Ce": 12,
        "Pr": 13,
        "Nd": 14,
        "Pm": 15,
        "Sm": 16,
        "Dy": 20,
        "Ho": 21,
        "Lu": 11,
        "Hf": 12,
        "Ta": 13,
        "W": 12,
        "Re": 15,
        "Os": 14,
        "Ir": 15,
        "Pt": 16,
        "Au": 17,
        "Hg": 18,
        "Tl": 19,
        "Pb": 14,
        "Bi": 15,
    }
}
