#!/bin/bash
#SBATCH -J job111_step4
#SBATCH -N 1
#SBATCH --ntasks-per-node 64
#SBATCH --exclusive
#SBATCH -p queue1-1
#SBATCH -t 144:00:00

module purge

source /public/home/yaodongqi/anaconda3/bin/activate
conda activate ML_DFT

# if [ -z "$1" ]; then
#   echo "请提供输入文件名作为参数。"
#   exit 1
# fi
# input_file="$1"

# python "$input_file"

python tdksen.py
