#!/bin/bash
#SBATCH -J job111_step3
#SBATCH -p queue1-1
#SBATCH -N 4
#SBATCH --ntasks-per-node 64 
#SBATCH --exclusive 
#SBATCH -t 144:00:00
export I_MPI_PMI_LIBRARY=/opt/gridview/slurm/lib/libpmi2.so
ulimit -s unlimited

module purge
module load compiler/intel/2021.3.0
module load mpi/intelmpi/2021.3.0
export UCX_TLS=dc,self

export PATH=/public/home/yaodongqi/VASP:$PATH
echo "============================================================"
env | grep "MKLROOT="
echo "============================================================"
echo "Job ID: $SLURM_JOB_NAME"
echo "Job name: $SLURM_JOB_NAME"
echo "Number of nodes: $SLURM_JOB_NUM_NODES"
echo "Number of processors: $SLURM_NTASKS"
echo "Task is running on the following nodes:"
echo $SLURM_JOB_NODELIST
echo "OMP_NUM_THREADS = $SLURM_CPUS_PER_TASK"
echo "============================================================"
# echo

# ln -sf /public/home/wbchu/src/VASP/vdw_kernel.bindat .

if [ -f KPOINTS ]; then
    # 提取 KPOINTS 文件第 4 行的三个方向的 K 点个数
    read kx ky kz <<< $(sed -n '4p' KPOINTS)

    # 计算三个方向的 K 点个数的乘积
    kpoints_product=$((kx * ky * kz))

    # 如果乘积为 1，则运行 vasp_gam，否则运行 vasp_std
    if [ "$kpoints_product" -eq 1 ]; then
        sed -i 's/.*KPAR.*/# KPAR   = 1/' INCAR
        srun --mpi=pmi2 vasp_gam
    else
        sed -i 's/.*KPAR.*/KPAR   = 2/' INCAR
        srun --mpi=pmi2 vasp_std
    fi
else
    echo "KPOINTS file not found. Exiting."
    exit 1
fi

rm CHG vasprun.xml
