#!/bin/bash
#SBATCH -J job111_step4
#SBATCH -N 1
#SBATCH --ntasks-per-node=64
#SBATCH --exclusive
#SBATCH -p queue1-1
#SBATCH -t 144:00:00
export I_MPI_PMI_LIBRARY=/opt/gridview/slurm/lib/libpmi2.so
ulimit -s unlimited

module purge
module load compiler/intel/2021.3.0
module load mpi/intelmpi/2021.3.0
export UCX_TLS=dc,self

export PATH=/public/home/yaodongqi/VASP:$PATH

#export I_MPI_PMI_LIBRARY=libpmi2.so

echo "============================================================"
module list
env | grep "MKLROOT ="
echo "============================================================"
echo "Job ID: $SLURM_JOB_NAME"
echo "Job name: $SLURM_JOB_NAME"
echo "Number of nodes: $SLURM_JOB_NUM_NODES"
echo "Number of processors: $SLURM_NTASKS"
echo "Task is running on the following nodes:"
echo $SLURM_JOB_NODELIST
echo "OMP_NUM_THREADS = $SLURM_CPUS_PER_TASK"
echo "============================================================"
echo

################################################################################
# Modified For LOOP
################################################################################
START=1
END=1250
NDIGIT=3
RUNDIR=${PWD}
PREFIX="../4_SCF"

for i in `seq ${START} ${END}`
do
    (( j = i - 1 ))
    ii=`printf "%0${NDIGIT}d" ${i}`
    jj=`printf "%0${NDIGIT}d" ${j}`

    if [[ -d "${PREFIX}/${ii}" ]]; then

        # goto the working directory
        cd ${PREFIX}/${ii}

        # Skip this directory if job is running or has ended
        if [[ -f RUNNING || -f ENDED ]]; then
            # Do nothing, go back to the parent directory
            cd ${RUNDIR}
            continue
        fi

        # Mark the directory as RUNNING
        touch RUNNING
        echo "#### RUNNING in DIR: ${RUNDIR}/${PREFIX}/${ii}"
        sleep 1

        # Copy the CHGCAR from the nearest finished job to accelerate current job
        [[ -s ../${jj}/CHGCAR && -f ../${jj}/ENDED ]] && cp ../${jj}/CHGCAR .

        ############################################################
        # Run VASP
        ############################################################
        srun --mpi=pmi2 vasp_gam
        ############################################################

        # Check if jobs ended correctly
        if grep 'Total CPU' OUTCAR >& /dev/null; then
            # If so, mark the job as ENDED
            touch ENDED
        else
            rm ENDED 2> /dev/null
        fi

        # Delete redundant files
        rm RUNNING CHG vasprun.xml >& /dev/null

        # Go back to the parent directory
        cd ${RUNDIR}
    fi
done
