#!/usr/bin/env python3
"""Generate a complete jf-remote project YAML from qdyn.yaml pool
definitions and jf_base.yaml infrastructure settings.

Usage:
    python scripts/generate_jf_config.py
    python scripts/generate_jf_config.py --qdyn-config config/qdyn.yaml
    python scripts/generate_jf_config.py --output /tmp/jf_test.yaml --dry-run

The script is idempotent: repeated runs produce identical output.
The output file is written atomically (write to temp, then rename).
"""

from __future__ import annotations

import argparse
import os
import sys
import tempfile
from pathlib import Path
from typing import Any, Dict

import yaml


# ---------------------------------------------------------------------------
# YAML output helpers
# ---------------------------------------------------------------------------

_HEADER = "# Auto-generated by generate_jf_config.py — DO NOT EDIT MANUALLY\n"


class _LiteralStr(str):
    """Tag for YAML literal block scalars (pre_run strings etc.)."""


def _literal_representer(dumper: yaml.Dumper, data: _LiteralStr) -> yaml.Node:
    return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")


yaml.add_representer(_LiteralStr, _literal_representer)


# ---------------------------------------------------------------------------
# Loading helpers
# ---------------------------------------------------------------------------


def _load_yaml(path: Path) -> Dict[str, Any]:
    """Load a YAML file and return its contents as a dict."""
    if not path.is_file():
        print(f"ERROR: file not found: {path}", file=sys.stderr)
        sys.exit(1)
    with open(path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)
    if not isinstance(data, dict):
        print(f"ERROR: {path} does not contain a YAML mapping", file=sys.stderr)
        sys.exit(1)
    return data


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------


def _validate(
    qdyn_cfg: Dict[str, Any],
    jf_base: Dict[str, Any],
    qdyn_path: Path,
    jf_base_path: Path,
) -> None:
    """Validate consistency between qdyn.yaml and jf_base.yaml."""
    errors: list[str] = []

    # jf_base must not contain workers
    if "workers" in jf_base:
        errors.append(
            f"{jf_base_path}: must not contain a 'workers' key. "
            "Workers are generated from qdyn.yaml worker_pools."
        )

    # qdyn.yaml must have basic.jf_project_name
    basic = qdyn_cfg.get("basic", {})
    jf_project_name = basic.get("jf_project_name")
    if not jf_project_name:
        errors.append(
            f"{qdyn_path}: missing 'basic.jf_project_name'"
        )

    # jf_base must have name
    jf_base_name = jf_base.get("name")
    if not jf_base_name:
        errors.append(f"{jf_base_path}: missing 'name' field")

    # Names must match
    if jf_project_name and jf_base_name and jf_project_name != jf_base_name:
        errors.append(
            f"Project name mismatch: qdyn.yaml basic.jf_project_name="
            f"'{jf_project_name}' vs jf_base.yaml name='{jf_base_name}'"
        )

    # Must have worker_pools
    if "worker_pools" not in qdyn_cfg:
        errors.append(
            f"{qdyn_path}: missing 'worker_pools' section"
        )
    else:
        pools = qdyn_cfg["worker_pools"]
        if not isinstance(pools, dict) or len(pools) == 0:
            errors.append(
                f"{qdyn_path}: 'worker_pools' must be a non-empty mapping"
            )
        else:
            for pool_name, pool_def in pools.items():
                if not isinstance(pool_def, dict):
                    errors.append(
                        f"{qdyn_path}: worker_pools.{pool_name} must be a mapping"
                    )
                    continue
                pool_params = pool_def.get("pool", {})
                if not pool_params.get("size"):
                    errors.append(
                        f"{qdyn_path}: worker_pools.{pool_name}.pool.size is required"
                    )
                if not pool_params.get("work_dir_base"):
                    errors.append(
                        f"{qdyn_path}: worker_pools.{pool_name}.pool.work_dir_base is required"
                    )

    # active_pool must reference a defined pool
    active_pool = qdyn_cfg.get("active_pool")
    if active_pool and "worker_pools" in qdyn_cfg:
        if active_pool not in qdyn_cfg["worker_pools"]:
            errors.append(
                f"{qdyn_path}: active_pool '{active_pool}' not found in worker_pools"
            )

    if errors:
        print("Validation failed:", file=sys.stderr)
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        sys.exit(1)


# ---------------------------------------------------------------------------
# Worker expansion
# ---------------------------------------------------------------------------


def _expand_pool_workers(
    pool_name: str, pool_def: Dict[str, Any]
) -> Dict[str, Dict[str, Any]]:
    """Expand a single pool definition into individual worker entries.

    Returns a dict mapping worker names to their jf-remote worker configs.
    Example: local_slurm with size=3 produces:
        local_slurm_001, local_slurm_002, local_slurm_003
    """
    pool_params = pool_def.get("pool", {})
    size: int = pool_params["size"]
    max_jobs: int = pool_params.get("max_jobs", 1)
    work_dir_base: str = pool_params["work_dir_base"]
    resources: dict = pool_params.get("resources", {})

    # Determine worker type from pool config (default: local)
    worker_type: str = pool_params.get("type", "local")
    scheduler_type: str = pool_params.get("scheduler_type", "slurm")

    workers: Dict[str, Dict[str, Any]] = {}
    # Zero-pad width: enough digits for the pool size
    pad = len(str(size))
    if pad < 3:
        pad = 3  # minimum 3 digits for readability

    for i in range(1, size + 1):
        worker_name = f"{pool_name}_{i:0{pad}d}"
        worker_cfg: Dict[str, Any] = {
            "type": worker_type,
            "scheduler_type": scheduler_type,
            "work_dir": os.path.join(work_dir_base, worker_name),
            "max_jobs": max_jobs,
        }
        if resources:
            worker_cfg["resources"] = dict(resources)
        workers[worker_name] = worker_cfg

    return workers


# ---------------------------------------------------------------------------
# Assembly
# ---------------------------------------------------------------------------


def _build_jf_config(
    qdyn_cfg: Dict[str, Any], jf_base: Dict[str, Any]
) -> Dict[str, Any]:
    """Merge jf_base infrastructure with expanded pool workers."""
    # Start from a copy of jf_base (contains name, queue, jobstore, runner, etc.)
    result: Dict[str, Any] = {}

    # Preserve key ordering: name first, then workers, then the rest
    result["name"] = jf_base["name"]

    # Expand all pools into workers
    all_workers: Dict[str, Dict[str, Any]] = {}
    pools = qdyn_cfg.get("worker_pools", {})
    for pool_name, pool_def in pools.items():
        pool_workers = _expand_pool_workers(pool_name, pool_def)
        all_workers.update(pool_workers)

    result["workers"] = all_workers

    # Copy remaining jf_base fields (queue, jobstore, runner, etc.)
    for key, value in jf_base.items():
        if key in ("name", "workers"):
            continue
        result[key] = value

    return result


# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------


def _dump_yaml(data: Dict[str, Any]) -> str:
    """Serialize the config dict to a YAML string."""
    return yaml.dump(
        data,
        default_flow_style=False,
        sort_keys=False,
        allow_unicode=True,
        width=120,
    )


def _atomic_write(path: Path, content: str) -> None:
    """Write content to path atomically via temp file + rename.

    The temp file is created in the same directory as the target so that
    os.rename() is guaranteed to be atomic (same filesystem).
    """
    target_dir = path.parent
    target_dir.mkdir(parents=True, exist_ok=True)

    fd, tmp_path = tempfile.mkstemp(
        dir=str(target_dir), prefix=".jf_config_", suffix=".tmp"
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(content)
        os.rename(tmp_path, str(path))
    except BaseException:
        # Clean up temp file on failure
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
        raise


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _resolve_default_paths() -> tuple[Path, Path, Path | None]:
    """Resolve default paths relative to the repo root (parent of scripts/)."""
    # Determine repo root: this script lives in <repo>/scripts/
    script_dir = Path(__file__).resolve().parent
    repo_root = script_dir.parent

    qdyn_path = repo_root / "config" / "qdyn.yaml"
    jf_base_path = repo_root / "config" / "jf_base.yaml"
    # output path comes from qdyn.yaml basic.jf_project_path (resolved later)
    return qdyn_path, jf_base_path, None


def main(argv: list[str] | None = None) -> None:
    default_qdyn, default_jf_base, _ = _resolve_default_paths()

    parser = argparse.ArgumentParser(
        description="Generate jf-remote project config from qdyn.yaml pool definitions.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--qdyn-config",
        type=Path,
        default=default_qdyn,
        help=f"Path to qdyn.yaml (default: {default_qdyn})",
    )
    parser.add_argument(
        "--jf-base",
        type=Path,
        default=default_jf_base,
        help=f"Path to jf_base.yaml (default: {default_jf_base})",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Output path (default: qdyn.yaml basic.jf_project_path)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print generated YAML to stdout instead of writing to file",
    )
    args = parser.parse_args(argv)

    # Load inputs
    qdyn_cfg = _load_yaml(args.qdyn_config)
    jf_base = _load_yaml(args.jf_base)

    # Validate
    _validate(qdyn_cfg, jf_base, args.qdyn_config, args.jf_base)

    # Determine output path
    output_path = args.output
    if output_path is None:
        jf_project_path = qdyn_cfg.get("basic", {}).get("jf_project_path", "")
        if not jf_project_path:
            print(
                "ERROR: no --output specified and basic.jf_project_path is empty",
                file=sys.stderr,
            )
            sys.exit(1)
        output_path = Path(jf_project_path).expanduser()

    # Build and serialize
    jf_config = _build_jf_config(qdyn_cfg, jf_base)
    yaml_content = _HEADER + "\n" + _dump_yaml(jf_config)

    # Output
    if args.dry_run:
        print(yaml_content, end="")
        return

    _atomic_write(output_path, yaml_content)

    # Summary
    pools = qdyn_cfg.get("worker_pools", {})
    total_workers = sum(
        p.get("pool", {}).get("size", 0) for p in pools.values()
    )
    print(f"Generated {output_path}")
    print(f"  Pools: {', '.join(pools.keys())}")
    print(f"  Total workers: {total_workers}")
    for pool_name, pool_def in pools.items():
        size = pool_def.get("pool", {}).get("size", 0)
        pad = max(3, len(str(size)))
        first = f"{pool_name}_{1:0{pad}d}"
        last = f"{pool_name}_{size:0{pad}d}"
        print(f"    {pool_name}: {first} .. {last} (size={size})")


if __name__ == "__main__":
    main()
