import io
import os
import shutil
from typing import Any, Dict, Optional, Union

import ase.io
import numpy as np
from ase import Atoms

from .input import (
    InputT,
    NVTInputT,
    NVEInputT,
    SCFInputT,
    SRInputT,
)


def input_prepare(
    input: InputT,
    stru: str,
    pp_path: str,
    orb_path: str,
    stru_format: str = 'vasp',
):
    """Initialize job: prepare input files in current working directory.

    Parameters
    ----------
    input : InputT
        Input parameters.
    stru : str
        Structure file content as string.
    pp_path : str
        Path to pseudopotential files.
    orb_path : str
        Path to orbital files (for SIESTA/ABACUS/OpenMX).
    stru_format : str
        Format of structure file (default: 'vasp').

    Returns
    -------
    tuple
        (software, structure)
    """
    software = input.basic_input.software
    structure = ase.io.read(io.StringIO(stru), format=stru_format)

    match software:
        case 'vasp':
            prepare_vasp_inputs(structure, pp_path)
        case 'cp2k':
            raise NotImplementedError("CP2K input preparation not implemented yet.")
        case 'siesta':
            raise NotImplementedError("SIESTA input preparation not implemented yet.")
        case 'abacus':
            raise NotImplementedError("ABACUS input preparation not implemented yet.")
        case 'openmx':
            raise NotImplementedError("OpenMX input preparation not implemented yet.")
        case _:
            raise ValueError(f"Unknown software: {software}")

    return software, structure


# ===========================================================================
# VASP specific functions
# ===========================================================================


def prepare_vasp_inputs(
    structure: Atoms,
    pp_path: str,
    kspacing: Optional[float] = None,
    incar_params: Optional[Dict] = None,
    step_input: Optional[Union[SRInputT, NVTInputT, NVEInputT, SCFInputT]] = None,
):
    """Prepare VASP input files (POSCAR, KPOINTS, POTCAR, INCAR) in current directory.

    Parameters
    ----------
    structure : Atoms
        Atomic structure.
    pp_path : str
        Path to VASP pseudopotential directory.
    kspacing : float, optional
        K-point spacing in 1/Å. Used to generate KPOINTS.
    incar_params : dict, optional
        Additional INCAR parameters (will override defaults).
    step_input : SRInputT | NVTInputT | NVEInputT | SCFInputT, optional
        Step-specific input parameters.
    """
    # Write POSCAR
    ase.io.write('POSCAR', structure, format='vasp')

    # Write KPOINTS
    if kspacing is not None:
        prepare_kpoints(structure, kspacing)

    # Write POTCAR
    if pp_path:
        prepare_potcar(structure, pp_path)

    # Write INCAR
    prepare_incar(incar_params=incar_params, step_input=step_input)


def prepare_kpoints(structure: Atoms, kspacing: float):
    """Generate KPOINTS file based on k-point spacing.

    Parameters
    ----------
    structure : Atoms
        Atomic structure (used to get cell parameters).
    kspacing : float
        K-point spacing in 1/Å.
    """
    cell = structure.get_cell()
    # Calculate reciprocal lattice vectors
    rec_cell = cell.reciprocal()

    # Number of k-points in each direction: N = |b| * kspacing + 1
    kpoints = []
    for i in range(3):
        length = np.linalg.norm(rec_cell[i])
        nk = max(1, int(length * kspacing + 0.5))
        kpoints.append(nk)

    with open('KPOINTS', 'w') as f:
        f.write("KPOINTS generated by QDYN\n")
        f.write("0\n")
        f.write("Gamma\n")
        f.write(f"{kpoints[0]} {kpoints[1]} {kpoints[2]}\n")
        f.write("0 0 0\n")


def prepare_potcar(structure: Atoms, pp_path: str):
    """Generate POTCAR file by concatenating pseudopotentials.

    Parameters
    ----------
    structure : Atoms
        Atomic structure (used to get element types).
    pp_path : str
        Path to VASP pseudopotential directory.
    """
    # Get unique elements in order of appearance
    symbols = structure.get_chemical_symbols()
    unique_symbols = []
    for s in symbols:
        if s not in unique_symbols:
            unique_symbols.append(s)

    with open('POTCAR', 'w') as outf:
        for symbol in unique_symbols:
            # Try common POTCAR naming conventions
            potcar_candidates = [
                os.path.join(pp_path, symbol, 'POTCAR'),
                os.path.join(pp_path, f'POTCAR.{symbol}'),
                os.path.join(pp_path, f'{symbol}_POTCAR'),
                os.path.join(pp_path, f'{symbol}/POTCAR'),
            ]

            potcar_file = None
            for candidate in potcar_candidates:
                if os.path.exists(candidate):
                    potcar_file = candidate
                    break

            if potcar_file is None:
                raise FileNotFoundError(
                    f"POTCAR for element {symbol} not found in {pp_path}. "
                    f"Tried: {potcar_candidates}"
                )

            with open(potcar_file, 'r') as inf:
                shutil.copyfileobj(inf, outf)


def prepare_incar():
    pass
