import io
import os
import shutil
from typing import Any, Dict, Optional, Union

import ase.io
import numpy as np
from ase import Atoms

from .input import (
    InputT,
    NVTInputT,
    NVEInputT,
    SCFInputT,
    SRInputT,
)


def job_initialize(
    input: InputT,
    stru: str,
    pp_path: str,
    orb_path: str,
    stru_format: str = 'vasp',
):
    """Initialize job: prepare input files in current working directory.

    Parameters
    ----------
    input : InputT
        Input parameters.
    stru : str
        Structure file content as string.
    pp_path : str
        Path to pseudopotential files.
    orb_path : str
        Path to orbital files (for SIESTA/ABACUS/OpenMX).
    stru_format : str
        Format of structure file (default: 'vasp').

    Returns
    -------
    tuple
        (software, structure)
    """
    software = input.basic_input.software
    structure = ase.io.read(io.StringIO(stru), format=stru_format)

    match software:
        case 'vasp':
            prepare_vasp_inputs(structure, pp_path)
        case 'cp2k':
            raise NotImplementedError("CP2K input preparation not implemented yet.")
        case 'siesta':
            raise NotImplementedError("SIESTA input preparation not implemented yet.")
        case 'abacus':
            raise NotImplementedError("ABACUS input preparation not implemented yet.")
        case 'openmx':
            raise NotImplementedError("OpenMX input preparation not implemented yet.")
        case _:
            raise ValueError(f"Unknown software: {software}")

    return software, structure


# ===========================================================================
# VASP specific functions
# ===========================================================================


def prepare_vasp_inputs(
    structure: Atoms,
    pp_path: str,
    kspacing: Optional[float] = None,
    incar_params: Optional[Dict] = None,
    step_input: Optional[Union[SRInputT, NVTInputT, NVEInputT, SCFInputT]] = None,
):
    """Prepare VASP input files (POSCAR, KPOINTS, POTCAR, INCAR) in current directory.

    Parameters
    ----------
    structure : Atoms
        Atomic structure.
    pp_path : str
        Path to VASP pseudopotential directory.
    kspacing : float, optional
        K-point spacing in 1/Å. Used to generate KPOINTS.
    incar_params : dict, optional
        Additional INCAR parameters (will override defaults).
    step_input : SRInputT | NVTInputT | NVEInputT | SCFInputT, optional
        Step-specific input parameters.
    """
    # Write POSCAR
    prepare_poscar(structure)

    # Write KPOINTS
    if kspacing is not None:
        prepare_kpoints(structure, kspacing)

    # Write POTCAR
    if pp_path:
        prepare_potcar(structure, pp_path)

    # Write INCAR
    prepare_incar(incar_params=incar_params, step_input=step_input)


def prepare_poscar(structure: Atoms):
    """Write POSCAR file from ASE Atoms object in current directory."""
    ase.io.write('POSCAR', structure, format='vasp')


def prepare_kpoints(structure: Atoms, kspacing: float):
    """Generate KPOINTS file based on k-point spacing.

    Parameters
    ----------
    structure : Atoms
        Atomic structure (used to get cell parameters).
    kspacing : float
        K-point spacing in 1/Å.
    """
    cell = structure.get_cell()
    # Calculate reciprocal lattice vectors
    rec_cell = cell.reciprocal()

    # Number of k-points in each direction: N = |b| * kspacing + 1
    kpoints = []
    for i in range(3):
        length = np.linalg.norm(rec_cell[i])
        nk = max(1, int(length * kspacing + 0.5))
        kpoints.append(nk)

    with open('KPOINTS', 'w') as f:
        f.write("KPOINTS generated by QDYN\n")
        f.write("0\n")
        f.write("Gamma\n")
        f.write(f"{kpoints[0]} {kpoints[1]} {kpoints[2]}\n")
        f.write("0 0 0\n")


def prepare_potcar(structure: Atoms, pp_path: str):
    """Generate POTCAR file by concatenating pseudopotentials.

    Parameters
    ----------
    structure : Atoms
        Atomic structure (used to get element types).
    pp_path : str
        Path to VASP pseudopotential directory.
    """
    # Get unique elements in order of appearance
    symbols = structure.get_chemical_symbols()
    unique_symbols = []
    for s in symbols:
        if s not in unique_symbols:
            unique_symbols.append(s)

    with open('POTCAR', 'w') as outf:
        for symbol in unique_symbols:
            # Try common POTCAR naming conventions
            potcar_candidates = [
                os.path.join(pp_path, symbol, 'POTCAR'),
                os.path.join(pp_path, f'POTCAR.{symbol}'),
                os.path.join(pp_path, f'{symbol}_POTCAR'),
                os.path.join(pp_path, f'{symbol}/POTCAR'),
            ]

            potcar_file = None
            for candidate in potcar_candidates:
                if os.path.exists(candidate):
                    potcar_file = candidate
                    break

            if potcar_file is None:
                raise FileNotFoundError(
                    f"POTCAR for element {symbol} not found in {pp_path}. "
                    f"Tried: {potcar_candidates}"
                )

            with open(potcar_file, 'r') as inf:
                shutil.copyfileobj(inf, outf)


def prepare_incar(
    incar_params: Optional[Dict] = None,
    step_input: Optional[Union[SRInputT, NVTInputT, NVEInputT, SCFInputT]] = None,
):
    """Generate INCAR file for VASP calculation.

    Parameters are applied in the following order (later overrides earlier):
    1. VASP_BASE_INCAR (always applied)
    2. step_input.to_vasp_incar() (from step-specific input model)
    3. incar_params argument
    4. Parsed parameters string from step_input

    Parameters
    ----------
    incar_params : dict, optional
        Additional INCAR parameters.
    step_input : SRInputT | NVTInputT | NVEInputT | SCFInputT, optional
        Step-specific input parameters.
    """
    # Start with base parameters
    incar = VASP_BASE_INCAR.copy()

    # Apply step-specific parameters
    if step_input is not None:
        incar.update(step_input.to_vasp_incar())

        # Parse and apply extra parameters string
        if hasattr(step_input, 'parameters') and step_input.parameters:
            extra = parse_incar_string(step_input.parameters)
            incar.update(extra)

    # Override with user-provided parameters
    if incar_params:
        incar.update(incar_params)

    # Write INCAR file
    write_incar(incar)


def write_incar(incar: Dict[str, Any], filename: str = 'INCAR'):
    """Write INCAR file.

    Parameters
    ----------
    incar : Dict[str, Any]
        Dictionary of INCAR parameters.
    filename : str
        Output filename (default: 'INCAR').
    """
    with open(filename, 'w') as f:
        for key, value in incar.items():
            formatted_value = format_incar_value(value)
            f.write(f'{key:<12} = {formatted_value}\n')


def format_incar_value(value: Any) -> str:
    """Format a value for VASP INCAR file.

    Parameters
    ----------
    value : Any
        The value to format.

    Returns
    -------
    str
        Formatted value string.
    """
    if isinstance(value, bool):
        return '.TRUE.' if value else '.FALSE.'
    elif isinstance(value, (list, tuple)):
        return ' '.join(str(v) for v in value)
    else:
        return str(value)


def parse_incar_string(params_str: str) -> Dict[str, Any]:
    """Parse an INCAR-style parameter string into a dictionary.

    Supports formats:
    - 'KEY=VALUE; KEY2=VALUE2; ...'
    - 'KEY=VALUE\\nKEY2=VALUE2\\n...'
    - Values: bool (.TRUE./.FALSE.), int, float, string, space-separated list

    Parameters
    ----------
    params_str : str
        Parameter string.

    Returns
    -------
    Dict[str, Any]
        Parsed parameters.
    """
    params: Dict[str, Any] = {}
    if not params_str or not params_str.strip():
        return params

    # Split by semicolons and newlines
    items = params_str.replace(';', '\n').split('\n')

    for item in items:
        item = item.strip()
        if not item or '=' not in item:
            continue

        key, value_str = item.split('=', 1)
        key = key.strip().upper()
        value_str = value_str.strip()

        params[key] = parse_incar_value(value_str)

    return params


def parse_incar_value(value_str: str) -> Any:
    """Parse a single INCAR value string to appropriate Python type.

    Parameters
    ----------
    value_str : str
        Value string from INCAR.

    Returns
    -------
    Any
        Parsed value.
    """
    value_str = value_str.strip()
    lower_val = value_str.lower()

    # Boolean
    if lower_val in ('.true.', 'true', 't', 'yes'):
        return True
    if lower_val in ('.false.', 'false', 'f', 'no'):
        return False

    # Space-separated list
    parts = value_str.split()
    if len(parts) > 1:
        return [parse_incar_value(p) for p in parts]

    # Single value: try int, then float, then string
    try:
        if '.' in value_str or 'e' in lower_val:
            return float(value_str)
        return int(value_str)
    except ValueError:
        return value_str


def job_initialize_vasp(structure, pp_path, orb_path):
    """Legacy function - use prepare_vasp_inputs instead."""
    prepare_vasp_inputs(structure, pp_path)
