import io
import os
import shutil
from typing import Dict, Optional

import ase.io
import numpy as np
from ase import Atoms

from .input import InputT


def job_initialize(
    input: InputT,
    stru: str,
    pp_path: str,
    orb_path: str,
    stru_format: str = 'vasp',
):
    """Initialize job: prepare input files in current working directory.
    
    Parameters
    ----------
    input : InputT
        Input parameters.
    stru : str
        Structure file content as string.
    pp_path : str
        Path to pseudopotential files.
    orb_path : str
        Path to orbital files (for SIESTA/ABACUS/OpenMX).
    stru_format : str
        Format of structure file (default: 'vasp').
    
    Returns
    -------
    tuple
        (software, structure)
    """
    software = input.basic_input.software
    structure = ase.io.read(io.StringIO(stru), format=stru_format)

    match software:
        case 'vasp':
            prepare_vasp_inputs(structure, pp_path)
        case 'cp2k':
            raise NotImplementedError("CP2K input preparation not implemented yet.")
        case 'siesta':
            raise NotImplementedError("SIESTA input preparation not implemented yet.")
        case 'abacus':
            raise NotImplementedError("ABACUS input preparation not implemented yet.")
        case 'openmx':
            raise NotImplementedError("OpenMX input preparation not implemented yet.")
        case _:
            raise ValueError(f"Unknown software: {software}")

    return software, structure


# ===========================================================================
# VASP specific functions
# ===========================================================================

def prepare_vasp_inputs(
    structure: Atoms,
    pp_path: str,
    kspacing: Optional[float] = None,
    encut: Optional[float] = None,
    incar_params: Optional[Dict] = None,
    step_type: str = 'nvt',
):
    """Prepare VASP input files (POSCAR, KPOINTS, POTCAR, INCAR) in current directory.
    
    Parameters
    ----------
    structure : Atoms
        Atomic structure.
    pp_path : str
        Path to VASP pseudopotential directory.
    kspacing : float, optional
        K-point spacing in 1/Å. Used to generate KPOINTS.
    encut : float, optional
        Plane-wave cutoff energy in eV.
    incar_params : dict, optional
        Additional INCAR parameters (will override defaults).
    step_type : str
        Type of calculation step ('sr', 'nvt', 'nve', 'scf').
    """
    # Write POSCAR
    prepare_poscar(structure)
    
    # Write KPOINTS (if kspacing is provided)
    if kspacing is not None:
        prepare_kpoints(structure, kspacing)
    
    # Write POTCAR
    if pp_path:
        prepare_potcar(structure, pp_path)
    
    # Write INCAR
    prepare_incar(encut=encut, params=incar_params, step_type=step_type)


def prepare_poscar(structure: Atoms):
    """Write POSCAR file from ASE Atoms object in current directory."""
    ase.io.write('POSCAR', structure, format='vasp')


def prepare_kpoints(structure: Atoms, kspacing: float):
    """Generate KPOINTS file based on k-point spacing.
    
    Parameters
    ----------
    structure : Atoms
        Atomic structure (used to get cell parameters).
    kspacing : float
        K-point spacing in 1/Å.
    """
    cell = structure.get_cell()
    # Calculate reciprocal lattice vectors
    rec_cell = cell.reciprocal()
    
    # Number of k-points in each direction: N = |b| * kspacing + 1
    kpoints = []
    for i in range(3):
        length = np.linalg.norm(rec_cell[i])
        nk = max(1, int(length * kspacing + 0.5))
        kpoints.append(nk)
    
    with open('KPOINTS', 'w') as f:
        f.write("KPOINTS generated by QDYN\n")
        f.write("0\n")
        f.write("Gamma\n")
        f.write(f"{kpoints[0]} {kpoints[1]} {kpoints[2]}\n")
        f.write("0 0 0\n")


def prepare_potcar(structure: Atoms, pp_path: str):
    """Generate POTCAR file by concatenating pseudopotentials.
    
    Parameters
    ----------
    structure : Atoms
        Atomic structure (used to get element types).
    pp_path : str
        Path to VASP pseudopotential directory.
    """
    # Get unique elements in order of appearance
    symbols = structure.get_chemical_symbols()
    unique_symbols = []
    for s in symbols:
        if s not in unique_symbols:
            unique_symbols.append(s)
    
    with open('POTCAR', 'w') as outf:
        for symbol in unique_symbols:
            # Try common POTCAR naming conventions
            potcar_candidates = [
                os.path.join(pp_path, symbol, 'POTCAR'),
                os.path.join(pp_path, f'POTCAR.{symbol}'),
                os.path.join(pp_path, f'{symbol}_POTCAR'),
                os.path.join(pp_path, f'{symbol}/POTCAR'),
            ]
            
            potcar_file = None
            for candidate in potcar_candidates:
                if os.path.exists(candidate):
                    potcar_file = candidate
                    break
            
            if potcar_file is None:
                raise FileNotFoundError(
                    f"POTCAR for element {symbol} not found in {pp_path}. "
                    f"Tried: {potcar_candidates}"
                )
            
            with open(potcar_file, 'r') as inf:
                shutil.copyfileobj(inf, outf)


def prepare_incar(
    encut: Optional[float] = None,
    params: Optional[Dict] = None,
    step_type: str = 'nvt',
):
    """Generate INCAR file for VASP calculation.
    
    Parameters
    ----------
    encut : float, optional
        Plane-wave cutoff energy in eV.
    params : dict, optional
        Additional INCAR parameters.
    step_type : str
        Type of calculation: 'sr' (structure relaxation), 
        'nvt' (NVT molecular dynamics), 'nve' (NVE molecular dynamics),
        'scf' (static SCF calculation).
    """
    # Base INCAR parameters (common to all calculations)
    incar = {
        'ISTART': 0,
        'ISPIN': 1,
        'LREAL': False,
        'PREC': 'Accurate',
        'LWAVE': False,
        'LCHARG': False,
        'NWRITE': 1,
        'KPAR': 2,
        'NCORE': 8,
        'ISMEAR': 0,
        'SIGMA': 0.1,
    }
    
    # Step-specific default parameters
    step_defaults = {
        'sr': {
            'NELM': 90,
            'NELMIN': 6,
            'EDIFF': 1e-8,
            'NSW': 100,
            'IBRION': 2,
            'ISIF': 2,
            'EDIFFG': -0.01,
        },
        'nvt': {
            'ALGO': 'Normal',
            'NELMIN': 4,
            'NELM': 120,
            'EDIFF': 1e-6,
            'ISYM': 0,
            'IBRION': 0,
            'NSW': 1000,
            'POTIM': 1,
            'SMASS': 0,
            'NBLOCK': 4,
            'TEBEG': 300,
            'TEEND': 300,
        },
        'nve': {
            'ALGO': 'Normal',
            'NELMIN': 4,
            'NELM': 120,
            'EDIFF': 1e-6,
            'ISYM': 0,
            'IBRION': 0,
            'NSW': 5000,
            'POTIM': 1,
            'SMASS': -3,
            'NBLOCK': 1,
        },
        'scf': {
            'LORBIT': 11,
            'NEDOS': 2001,
            'NELM': 120,
            'EDIFF': 1e-6,
        },
    }
    
    if step_type in step_defaults:
        incar.update(step_defaults[step_type])
    
    # Add ENCUT if provided
    if encut is not None:
        incar['ENCUT'] = encut
    
    # Override with user-provided parameters
    if params:
        incar.update(params)
    
    # Write INCAR
    with open('INCAR', 'w') as f:
        for key, value in incar.items():
            if isinstance(value, bool):
                value = '.TRUE.' if value else '.FALSE.'
            elif isinstance(value, float):
                if value < 1e-4 and value > 0:
                    value = f'{value:.1e}'
                else:
                    value = str(value)
            f.write(f'{key:<12} = {value}\n')


def job_initialize_vasp(structure, pp_path, orb_path):
    """Legacy function - use prepare_vasp_inputs instead."""
    prepare_vasp_inputs(structure, pp_path)
